//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoArea
    {
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> AreaTypeId { get; set; }
        public string AreaTypeName { get; set; }
        public string AreaLocationCode { get; set; }
        public Nullable<int> AreaDistrictId { get; set; }
        public Nullable<int> AreaProvineId { get; set; }
        public Nullable<int> AreaParentId { get; set; }
    }
}
