//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaContent
    {
        public long Id { get; set; }
        public long ObjectTypeId { get; set; }
        public string ObjectName { get; set; }
        public long IdType { get; set; }
        public string TypeName { get; set; }
        public long IdItem { get; set; }
        public string ItemName { get; set; }
        public bool Active { get; set; }
        public string Urlthumbnail { get; set; }
        public string UrlFull { get; set; }
        public string Link { get; set; }
        public int Status { get; set; }
    }
}
