//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostItem
    {
        public long Id { get; set; }
        public long IdType { get; set; }
        public string TypeName { get; set; }
        public Nullable<long> IdTypeNews { get; set; }
        public string TypeNewsName { get; set; }
        public Nullable<long> IdTypeParent { get; set; }
        public string TypeParentName { get; set; }
        public long IdProvince { get; set; }
        public string ProvinceName { get; set; }
        public long IdDistrict { get; set; }
        public string DistrictName { get; set; }
        public long IdWard { get; set; }
        public string WardName { get; set; }
        public long Unit { get; set; }
        public string UnitName { get; set; }
        public double Price { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Model { get; set; }
        public string Location { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string RoomNum { get; set; }
        public string Toilet { get; set; }
        public int Exprires { get; set; }
        public string Avatar { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool CreateByAdmin { get; set; }
        public int Status { get; set; }
        public string PhoneContact { get; set; }
        public string FriendlyUrl { get; set; }
        public string MetaAuthor { get; set; }
        public string MetaSeoKeyword { get; set; }
        public string MetaSeoDescription { get; set; }
        public Nullable<double> Horizontal { get; set; }
        public Nullable<double> Vertical { get; set; }
        public string FullAddress { get; set; }
        public long CountView { get; set; }
    }
}
