//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type()
        {
            this.LstTypes = new HashSet<Type>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentId { get; set; }
        public long ObjectTypeId { get; set; }
        public string ObjectTypeName { get; set; }
        public System.DateTime DateCreate { get; set; }
        public long UserCreate { get; set; }
        public string ClassIcon { get; set; }
        public int Status { get; set; }
    
        public virtual ObjectType ObjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type> LstTypes { get; set; }
        public virtual Type ObjType { get; set; }
    }
}
